[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.min.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.min.js"
[[params.plugins.js]]
link = "plugins/rellax/rellax.min.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"
[params.variables]
black = "#000000"
h1 = "48px"
h1_md = "38px"
h2 = "38px"
h2_md = "30px"
h3 = "22px"
h3_md = "20px"
h4 = "18px"
h5 = "16px"
h6 = "15px"
icon_font = "Line Awesome Free"
light = "#FAFAFA"
primary_color = "#FE6019"
primary_font = "Poppins:wght@400;500;600"
primary_font_type = "sans-serif"
secondary_font = ""
secondary_font_type = ""
white = "#ffffff"
